# Generated by Django 3.1.3 on 2022-04-01 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_avodha_app', '0002_auto_20220331_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='images',
            new_name='img',
        ),
    ]
